"""
Fisher-adaptive sampler for Ollama token generation (context continuation).

Mechanism:
  - generate short chunks per request (default 16 tokens)
  - compute token entropy from logprobs
  - every N tokens, compute sliding-window Fisher trace
  - adapt temperature/top_p according to threshold profile
"""

from __future__ import annotations

import argparse
import csv
import json
import os
from pathlib import Path
from typing import Any

from llm_entropy.entropy import entropy_from_top_logprobs
from llm_entropy.ollama_client import _post_json
from sliding_fisher import SlidingFisherTrace


def _clamp(x: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, x))


def _pick_thresholds(profile: dict[str, Any], regime: str) -> tuple[float, float]:
    by_regime = profile.get("regimes", {})
    default_low = float(profile.get("default_low_trace_threshold", 52.0))
    default_high = float(profile.get("default_high_trace_threshold", default_low * 1.35))
    if regime in by_regime:
        r = by_regime[regime]
        low = float(r.get("low_trace_threshold", default_low))
        high = float(r.get("high_trace_threshold", default_high))
        return low, high
    return default_low, default_high


def _step_generate_chunk(
    *,
    base_url: str,
    model: str,
    prompt: str,
    context: list[int] | None,
    top_logprobs: int,
    temperature: float,
    top_p: float,
    seed: int | None,
    num_ctx: int | None,
    num_predict: int,
) -> dict[str, Any]:
    options: dict[str, Any] = {
        "temperature": float(temperature),
        "top_p": float(top_p),
        "num_predict": int(num_predict),
        "stop": [],
    }
    if seed is not None and context is None:
        options["seed"] = int(seed)
    if num_ctx is not None:
        options["num_ctx"] = int(num_ctx)
    payload: dict[str, Any] = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "logprobs": True,
        "top_logprobs": int(top_logprobs),
        "options": options,
    }
    if context is not None:
        payload["context"] = context
    return _post_json(base_url.rstrip("/") + "/api/generate", payload, timeout_s=120.0)


def main() -> None:
    ap = argparse.ArgumentParser(description="Fisher-adaptive Ollama sampler")
    ap.add_argument("--ollama-url", default=os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11434"))
    ap.add_argument("--model", default="qwen2.5-coder:7b")
    ap.add_argument("--prompt", required=True)
    ap.add_argument("--regime", default="default")
    ap.add_argument("--max-tokens", type=int, default=512)
    ap.add_argument("--top-logprobs", type=int, default=15)
    ap.add_argument("--window-size", type=int, default=128)
    ap.add_argument("--fisher-check-every", type=int, default=16)
    ap.add_argument("--chunk-tokens", type=int, default=16)
    ap.add_argument("--fisher-epsilon", type=float, default=1e-10)
    ap.add_argument("--alphabet-size", type=int, default=7)
    ap.add_argument("--sax-behavior", choices=("quantile", "gaussian"), default="quantile")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--num-ctx", type=int, default=None)
    ap.add_argument("--temperature-init", type=float, default=0.6)
    ap.add_argument("--top-p-init", type=float, default=0.92)
    ap.add_argument("--temperature-min", type=float, default=0.2)
    ap.add_argument("--temperature-max", type=float, default=1.1)
    ap.add_argument("--top-p-min", type=float, default=0.75)
    ap.add_argument("--top-p-max", type=float, default=0.98)
    ap.add_argument("--temp-step-down", type=float, default=0.08)
    ap.add_argument("--temp-step-up", type=float, default=0.04)
    ap.add_argument("--topp-step-down", type=float, default=0.04)
    ap.add_argument("--topp-step-up", type=float, default=0.02)
    ap.add_argument(
        "--profile-json",
        default="results/llm_entropy/fisher_runs/fisher_baseline_profiles.json",
        help="Threshold profile generated by calibration script",
    )
    ap.add_argument("--out-csv", default="results/llm_entropy/fisher_runs/fisher_adaptive_trace.csv")
    ap.add_argument("--out-text", default="results/llm_entropy/fisher_runs/fisher_adaptive_output.txt")
    args = ap.parse_args()

    profile = {"default_low_trace_threshold": 52.0, "regimes": {}}
    if os.path.isfile(args.profile_json):
        with open(args.profile_json, "r", encoding="utf-8") as f:
            profile = json.load(f)
    low_threshold, high_threshold = _pick_thresholds(profile, args.regime)

    tracker = SlidingFisherTrace(
        window_size=args.window_size,
        alphabet_size=args.alphabet_size,
        sax_behavior=args.sax_behavior,
        fisher_epsilon=args.fisher_epsilon,
    )

    out_csv_path = Path(args.out_csv)
    out_csv_path.parent.mkdir(parents=True, exist_ok=True)
    with out_csv_path.open("w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerow(
            [
                "step",
                "token",
                "entropy",
                "fisher_trace",
                "temperature",
                "top_p",
                "action",
            ]
        )

    text_parts: list[str] = []
    context: list[int] | None = None
    prompt_use = args.prompt
    temperature = float(args.temperature_init)
    top_p = float(args.top_p_init)
    high_streak = 0

    step = 0
    while step < args.max_tokens:
        need = args.max_tokens - step
        response = _step_generate_chunk(
            base_url=args.ollama_url,
            model=args.model,
            prompt=prompt_use,
            context=context,
            top_logprobs=args.top_logprobs,
            temperature=temperature,
            top_p=top_p,
            seed=args.seed,
            num_ctx=args.num_ctx,
            num_predict=min(args.chunk_tokens, need),
        )
        logprobs = response.get("logprobs") or []
        if not logprobs:
            break
        for token_step in logprobs:
            token = str(token_step.get("token", ""))
            entropy = float(entropy_from_top_logprobs(token_step))
            text_parts.append(token)

            fisher_trace = tracker.update(entropy)
            action = "hold"
            if fisher_trace is not None and (step + 1) % args.fisher_check_every == 0:
                if fisher_trace < low_threshold:
                    temperature = _clamp(temperature - args.temp_step_down, args.temperature_min, args.temperature_max)
                    top_p = _clamp(top_p - args.topp_step_down, args.top_p_min, args.top_p_max)
                    high_streak = 0
                    action = "focus_down"
                elif fisher_trace > high_threshold:
                    high_streak += 1
                    if high_streak >= 2:
                        temperature = _clamp(temperature + args.temp_step_up, args.temperature_min, args.temperature_max)
                        top_p = _clamp(top_p + args.topp_step_up, args.top_p_min, args.top_p_max)
                        action = "explore_up"
                else:
                    high_streak = 0

            with out_csv_path.open("a", newline="", encoding="utf-8") as f:
                csv.writer(f).writerow(
                    [
                        step,
                        token,
                        f"{entropy:.8f}",
                        "" if fisher_trace is None else f"{fisher_trace:.8f}",
                        f"{temperature:.4f}",
                        f"{top_p:.4f}",
                        action,
                    ]
                )
            print(
                f"{step}\tH={entropy:.5f}\tF={fisher_trace if fisher_trace is not None else float('nan'):.4f}\t"
                f"T={temperature:.3f}\tP={top_p:.3f}\t{action}\t{token!r}",
                flush=True,
            )
            step += 1
            if step >= args.max_tokens:
                break

        context = response.get("context")
        if step >= args.max_tokens:
            break
        if context is not None:
            prompt_use = ""
            continue
        piece = str(response.get("response", ""))
        if not piece:
            break
        prompt_use += piece

    out_text_path = Path(args.out_text)
    out_text_path.parent.mkdir(parents=True, exist_ok=True)
    out_text_path.write_text("".join(text_parts), encoding="utf-8")
    print(f"\nOutput text: {out_text_path}")
    print(f"Trace CSV:   {out_csv_path}")


if __name__ == "__main__":
    main()
